## @file
# Dependabot configuration file to enable Github services
# for managing and updating dependencies.

version: 2 # Dependabot Config File Scheme as of April 2026
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "pip"
    reviewers:
      - "dhaggitt"
      - "efutey15"
      - "ThePieBaker90"
      - "Allo-DinoMage"
      - "Royer5000"
    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "GitHub Action"
    reviewers:
      - "dhaggitt"
      - "efutey15"
      - "ThePieBaker90"
      - "Allo-DinoMage"
      - "Royer5000"
    rebase-strategy: "disabled"