# Generated by Django 4.2.11 on 2026-03-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('storefront', models.CharField(default='steam', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game_id', models.IntegerField()),
            ],
        ),
    ]
