# Generated by Django 4.2.11 on 2026-03-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
