# Generated by Django 4.2.11 on 2026-03-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
    ]
