# Generated by Django 4.2.11 on 2026-03-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_game_slug'),
    ]

    operations = [
    ]
