# Generated by Django 4.2.11 on 2026-03-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_merge_20260331_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='storefront',
            field=models.CharField(default='steam', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='game_thumbnails/'),
        ),
    ]
