# Generated by Django 4.2.11 on 2026-04-06 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_game_game_id_game_publisher_game_storefront_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
