# Generated by Django 4.2.11 on 2026-04-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_game_game_id_game_publisher_game_storefront_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
