# Generated by Django 4.2.11 on 2026-04-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_game_developer'),
        ('home', '0005_game_authorized_users_game_uploaded_by_and_more'),
    ]

    operations = [
    ]
