# Generated by Django 6.0.4 on 2026-04-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_game_developer'),
        ('home', '0005_game_authorized_users_game_uploaded_by_and_more'),
    ]

    operations = [
    ]
