# Generated by Django 4.2.11 on 2026-04-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20260418_0150'),
        ('home', '0006_merge_20260420_2010'),
        ('home', '0007_adding_similar_games'),
        ('home', '0007_alter_game_slug'),
    ]

    operations = [
    ]
