# Generated by Django 4.2.11 on 2026-04-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20260420_2307'),
        ('home', '0008_merge_20260420_2323'),
    ]

    operations = [
    ]
